opentelemetry-collector:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      opencensus: {}
      # zipkin:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
          # thrift_binary:
    processors:
      batch: {}
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter: null
    extensions:
      health_check: {}
      memory_ballast: {}
    # If set to null, will be overridden with v
    exporters:
      otlp:
        endpoint: tempo-distributed-distributor.tempo-distributed:4317
        tls:
          insecure: true
    service:
      extensions: [health_check, memory_ballast]
      pipelines:
        traces:
          receivers: [otlp, jaeger, opencensus]
          processors:
            - memory_limiter
            - batch
          exporters: [otlp]

  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "200m"
      memory: 300Mi
