apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-grafana-datasource'
  labels:
    app: '{{ .Release.Name }}'
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        version: 1
        editable: false
        apiVersion: 1
        access: proxy
        orgId: 1
        url: http://{{(include "loki.gatewayFullname" .)}}.{{ .Release.Namespace }}.svc.{{ (index .Values "loki-distributed").global.clusterDomain }}:80
        isDefault: false
        jsonData:
          maxLines: 100
          derivedFields:
            # Field with internal link pointing to data source in Grafana.
            # datasourceUid value can be anything, but it should be unique across all defined data source uids.
            - datasourceUid: tempo
              # regexp to support `traceID=...` (in text) and `trace_id": "...` (in json)
              matcherRegex: "(?:traceID|trace_id)\"?\\s*[=:]\\s*\"?(\\w+)"
              name: TraceID
              # url will be interpreted as query for the datasource
              url: '$${__value.raw}'
            # severalfields can not share same name
            # # Field with external link.
            # - matcherRegex: "traceID=(\\w+)"
            #   name: TraceID
            #   url: 'http://localhost:16686/trace/$${__value.raw}'
