grafana:
  rbac:
    pspEnabled: false

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 60
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 60

  env:
    GF_AUTH_ANONYMOUS_ENABLED: true
    GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    GF_AUTH_DISABLE_LOGIN_FORM: true
    # GF_FEATURE_TOGGLES_ENABLE: tempoSearch tempoBackendSearch

  # datasources:
  #   datasources.yaml:
  #     apiVersion: 1

  #     datasources:
  #       - name: Tempo
  #         type: tempo
  #         access: proxy
  #         orgId: 1
  #         url: http://tempo-tempo-distributed-query-frontend:3100
  #         basicAuth: false
  #         isDefault: true
  #         version: 1
  #         editable: false
  #         apiVersion: 1
  #         uid: tempo
  ## Timezone for the default dashboards
  ## Other options are: browser or a specific timezone, i.e. Europe/Luxembourg
  ##
  defaultDashboardsTimezone: utc
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      searchNamespace: ALL
