# config to launch a cluster with kind
# to have a more reproducible setup
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # for image ref, see [release](https://github.com/kubernetes-sigs/kind/releases)
  - role: control-plane
    image: kindest/node:v1.24.15@sha256:7db4f8bea3e14b82d12e044e25e34bd53754b7f2b0e9d56df21774e6f66a70ab
  - role: worker
    image: kindest/node:v1.24.15@sha256:7db4f8bea3e14b82d12e044e25e34bd53754b7f2b0e9d56df21774e6f66a70ab
