repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: "jetstack"
    url: "https://charts.jetstack.io"
  - name: "minio-legacy"
    url: "https://helm.min.io/"
  - name: "grafana"
    url: "https://grafana.github.io/helm-charts"
  - name: "prometheus-community"
    url: "https://prometheus-community.github.io/helm-charts"
  - name: "open-telemetry"
    url: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  # - name: "linkerd"
  #   url: "https://helm.linkerd.io/stable"
  # - name: "pixie-operator"
  #   url: "https://pixie-operator-charts.storage.googleapis.com"

releases:
  - name: "cert-manager"
    namespace: "cert-manager"
    chart: "./cert-manager"
  - name: "minio"
    namespace: "minio"
    chart: "./minio"
  - name: "grafana"
    namespace: "grafana"
    chart: "./grafana"
  - name: "kube-prometheus-stack"
    namespace: "kube-prometheus-stack"
    chart: "./kube-prometheus-stack"
    needs:
      - "grafana/grafana"
  - name: "loki-distributed"
    namespace: "loki-distributed"
    chart: "./loki-distributed"
    needs:
      - "minio/minio"
      - "grafana/grafana"
  - name: "promtail"
    namespace: "promtail"
    chart: "./promtail"
    needs:
      - "loki-distributed/loki-distributed"
  - name: "tempo-distributed"
    namespace: "tempo-distributed"
    chart: "./tempo-distributed"
    needs:
      - "minio/minio"
      - "grafana/grafana"
  - name: "opentelemetry-operator"
    namespace: "opentelemetry-operator"
    chart: "./opentelemetry-operator"
    needs:
      - "cert-manager/cert-manager"
      - "tempo-distributed/tempo-distributed"
  # - name: "linkerd"
  #   namespace: "linkerd"
  #   chart: "./linkerd"
  # - name: "linkerd-viz"
  #   namespace: "linkerd-viz"
  #   chart: "./linkerd-viz"
  #   needs:
  #     - "linkerd/linkerd"
  #     - "grafana/grafana"
  #     - "kube-prometheus-stack/kube-prometheus-stack"
