apiVersion: v1
kind: Service
metadata:
  labels:
    name: minio
  name: minio
spec:
  ports:
  - name: service
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: minio
    name: minio
