linkerd-viz:
  installNamespace: true
  linkerdNamespace: linkerd
  dashboard:
    enforcedHostRegexp: ".*"
  prometheusUrl: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090/
  # additional scrapeconfig defined into prometheus chart for linkerd
  prometheus:
    enabled: false
  grafanaUrl: http://grafana.grafana:80/
  grafana:
    enabled: false
    uidPrefix: "demo-desktop"
    # externalUrl: http://localhost:80/

# copied from https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/values.yaml
# but the download of the file , to then used by configmap is done by an external script
dashboards:
  # all these charts are hosted at https://grafana.com/grafana/dashboards/{id}
  top-line:
    gnetId: 15474
    revision: 3
    datasource: prometheus
  health:
    gnetId: 15486
    revision: 2
    datasource: prometheus
  kubernetes:
    gnetId: 15479
    revision: 2
    datasource: prometheus
  namespace:
    gnetId: 15478
    revision: 2
    datasource: prometheus
  deployment:
    gnetId: 15475
    revision: 5
    datasource: prometheus
  pod:
    gnetId: 15477
    revision: 2
    datasource: prometheus
  service:
    gnetId: 15480
    revision: 2
    datasource: prometheus
  route:
    gnetId: 15481
    revision: 2
    datasource: prometheus
  authority:
    gnetId: 15482
    revision: 2
    datasource: prometheus
  cronjob:
    gnetId: 15483
    revision: 2
    datasource: prometheus
  job:
    gnetId: 15487
    revision: 2
    datasource: prometheus
  daemonset:
    gnetId: 15484
    revision: 2
    datasource: prometheus
  replicaset:
    gnetId: 15491
    revision: 2
    datasource: prometheus
  statefulset:
    gnetId: 15493
    revision: 2
    datasource: prometheus
  replicationcontroller:
    gnetId: 15492
    revision: 2
    datasource: prometheus
  prometheus:
    gnetId: 15489
    revision: 2
    datasource: prometheus
  prometheus-benchmark:
    gnetId: 15490
    revision: 2
    datasource: prometheus
  multicluster:
    gnetId: 15488
    revision: 2
    datasource: prometheus
