apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-grafana-datasource'
  labels:
    app: '{{ .Release.Name }}'
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: server
        orgId: 1
        url: http://{{ include "tempo.queryFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ (index .Values "tempo-distributed").global.clusterDomain }}:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
        uid: tempo
