apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-grafana-datasource'
  labels:
    app: '{{ .Release.Name }}'
    grafana_datasource: '1'
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        version: 1
        editable: true
        apiVersion: 1
        access: proxy
        orgId: 1
        url: http://{{ include "tempo.queryFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ (index .Values "tempo-distributed").global.clusterDomain }}:3100
        basicAuth: false
        isDefault: false
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            mapTagNamesEnabled: false
            spanStartTimeShift: '5m'
            spanEndTimeShift: '5m'
            filterByTraceID: true
            filterBySpanID: false
          serviceMap:
            datasourceUid: 'prometheus'
          search:
            hide: false
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: 'loki'
