
version: "3"
services:

  # # Generate fake traces...
  # synthetic-load-generator:
  #   image: omnition/synthetic-load-generator:1.0.25
  #   volumes:
  #     - ../shared/load-generator.json:/etc/load-generator.json
  #   environment:
  #     - TOPOLOGY_FILE=/etc/load-generator.json
  #     - JAEGER_COLLECTOR_URL=http://otel-collector:14268

  # And put them in an OTEL collector pipeline...
  otel-collector:
    image: otel/opentelemetry-collector:0.32.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      # - "14268:14268"  # jaeger ingest
      # - "4317:4317"  # otlp grpc
      # - "4318:4318"  # otlp http
      # - "9411:9411"   # zipkin

  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.1.6
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
