promtail:
  config:
    logLevel: warn
    clients:
      # see https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push
      - url: http://loki-distributed-distributor.loki-distributed.svc.cluster.local:3100/loki/api/v1/push
