apiVersion: v2
name: minio
description: An adapter chart for minio (the deprecated)
type: application
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://artifacthub.io/packages/helm/minio/minio
version: 8.0.10
appVersion: "2021"
dependencies:
  - name: "minio"
    version: "8.0.10"
    repository: "https://helm.min.io/"
