collector:
  mode: sidecar
  sidecarNamespaces: ["app", "grafana"]
  config:
    exporters:
      otlp:
        endpoint: tempo-distributed-distributor.tempo-distributed:4317

opentelemetry-operator:
  admissionWebhooks:
    certManager:
      enabled: true
